name       : pipx
version    : 1.0.0
release    : 4
source     :
    - https://github.com/pypa/pipx/archive/refs/tags/1.0.0.tar.gz : 6411399e6d323161983cab9c997e5ad819b7198a9965f0d5797e5e9f7760d908
license    : MIT
component  : programming.python
summary    : Install and Run Python Applications in Isolated Environments
description: |
    pipx is a tool to help you install and run end-user applications written in Python. It uses pip, but is focused on installing and managing Python packages that can be run from the command line directly as applications.
builddeps  :
    - python-argcomplete
rundeps    :
    - python-argcomplete
    - python-packaging
    - python-userpath
build      : |
    %python3_setup
install    : |
    %python3_install

    mkdir -p $workdir/completions
    register-python-argcomplete --shell bash pipx > $workdir/completions/pipx.bash
    install -Dm00644 $workdir/completions/pipx.bash $installdir/usr/share/bash-completion/completions/pipx
    register-python-argcomplete --shell fish pipx > $workdir/completions/pipx.fish
    install -Dm00644 $workdir/completions/pipx.fish $installdir/usr/share/fish/vendor_completions.d/pipx.fish
