name       : pipx
version    : 0.17.0
release    : 2
source     :
    - https://github.com/pypa/pipx/archive/refs/tags/0.17.0.tar.gz : 8d72b40b618cbc155bffb8fe02a00d8c05dcd12a94134cd0f6e2c5b6a5a92073
license    : MIT
component  : programming.python
summary    : Install and Run Python Applications in Isolated Environments
description: |
    pipx is a tool to help you install and run end-user applications written in Python. It uses pip, but is focused on installing and managing Python packages that can be run from the command line directly as applications.
builddeps  :
    - python-argcomplete
rundeps    :
    - python-argcomplete
    - python-packaging
    - python-userpath
build      : |
    %python3_setup
install    : |
    %python3_install

    mkdir -p $workdir/completions
    register-python-argcomplete --shell bash pipx > $workdir/completions/pipx.bash
    install -Dm00644 $workdir/completions/pipx.bash $installdir/usr/share/bash-completion/completions/pipx
    register-python-argcomplete --shell fish pipx > $workdir/completions/pipx.fish
    install -Dm00644 $workdir/completions/pipx.fish $installdir/usr/share/fish/vendor_completions.d/pipx.fish
