name       : pipx
version    : 1.2.0
release    : 5
source     :
    - https://github.com/pypa/pipx/archive/refs/tags/1.2.0.tar.gz : 4ccfb259ce7036c808397ee131de53ea4283fcbfe06c9fb23dcc84c440e3d09d
homepage   : https://pypa.github.io/pipx/
license    : MIT
component  : programming.python
summary    : Install and Run Python Applications in Isolated Environments
description: |
    pipx is a tool to help you install and run end-user applications written in Python. It uses pip, but is focused on installing and managing Python packages that can be run from the command line directly as applications.
builddeps  :
    - python-argcomplete
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-argcomplete
    - python-packaging
    - python-userpath
build      : |
    %python3_setup
install    : |
    %python3_install

    mkdir -p $workdir/completions
    register-python-argcomplete --shell bash pipx > $workdir/completions/pipx.bash
    install -Dm00644 $workdir/completions/pipx.bash $installdir/usr/share/bash-completion/completions/pipx
    register-python-argcomplete --shell fish pipx > $workdir/completions/pipx.fish
    install -Dm00644 $workdir/completions/pipx.fish $installdir/usr/share/fish/vendor_completions.d/pipx.fish
