name       : pipx
version    : 0.16.5
release    : 1
source     :
    - https://github.com/pypa/pipx/archive/refs/tags/0.16.5.tar.gz : 88b10fb8e4425b97acc9bbbbf93cb97ae9b23fc7a95777970e4f3eb849848bf9
license    : MIT
component  : programming.python
summary    : Install and Run Python Applications in Isolated Environments
description: |
    pipx is a tool to help you install and run end-user applications written in Python. It uses pip, but is focused on installing and managing Python packages that can be run from the command line directly as applications.
builddeps  :
    - python-argcomplete
rundeps    :
    - python-argcomplete
    - python-packaging
    - python-userpath
build      : |
    %python3_setup
install    : |
    %python3_install

    mkdir -p $workdir/completions
    register-python-argcomplete --shell bash pipx > $workdir/completions/pipx.bash
    install -Dm00644 $workdir/completions/pipx.bash $installdir/usr/share/bash-completion/completions/pipx
    register-python-argcomplete --shell fish pipx > $workdir/completions/pipx.fish
    install -Dm00644 $workdir/completions/pipx.fish $installdir/usr/share/fish/vendor_completions.d/pipx.fish
